name: Build and Test

on: [push, pull_request]

jobs:

  unit-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tests
    steps:
      - uses: actions/checkout@v3
      - name: Node version
        run: node -v
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test-headless

  end-to-end-test:

    runs-on: ubuntu-latest
    needs: [unit-test]
    services:
      chrome:
        image: selenium/standalone-chrome:3.141.59-20200525
        ports:
          - 4444:4444
          - 9060:5900
        options: --shm-size=2gb
        env:
          VNC_NO_PASSWORD: 1
      firefox:
        image: selenium/standalone-firefox:3.141.59-20210929
        ports:
          - 4444:4444
          - 9059:5900
        options: --shm-size=2gb
        env:
          VNC_NO_PASSWORD: 1
    strategy:
      matrix:
        include:
          - selenium-browser: "chrome"
            build-env: "build.prod"
          - selenium-browser: "chrome"
            build-env: "build.nonmin.travis"
          - selenium-browser: "firefox"
            build-env: "build.prod"
          - selenium-browser: "firefox"
            build-env: "build.nonmin.travis"
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: tests

    env:
      SELENIUM_BROWSER: ${{ matrix.selenium-browser }}
      BUILD_ENV: ${{ matrix.build-env }}

    steps:
      - uses: actions/checkout@v3
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
      - name: Build
        run: |
          npm ci
          npm run ${BUILD_ENV}
      - name: Test
        run: |
          codeceptjs -c ./tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --invert --grep '@optional'
          pwd
          ls -la codeceptjs/output
      - name: Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: codeceptjs-output
          path: tests/codeceptjs/output
          retention-days: 30
      - name: Test (optional)
        continue-on-error: true
        run: codeceptjs -c ./tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --grep '@optional'

