name: Build and Test

on: [push, pull_request]

jobs:

  unit-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node version
        run: node -v
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test-headless

  end-to-end-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - selenium-browser: "chrome"
            build-env: "build.prod"
          - selenium-browser: "chrome"
            build-env: "build.nonmin.travis"
          - selenium-browser: "firefox"
            build-env: "build.prod"
          - selenium-browser: "firefox"
            build-env: "build.nonmin.travis"
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: tests

    env:
      SELENIUM_BROWSER: ${{ matrix.selenium-browser }}
      BUILD_ENV: ${{ matrix.build-env }}

    steps:
      - uses: actions/checkout@v3
      #- name: Install
      #  run: |
      #    npm install
      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
      - name: Start
        run: docker-compose up -d ${SELENIUM_BROWSER}
      - name: Build
        run: docker-compose run -T --rm node npm run ${BUILD_ENV}
      - name: Test
        run: |
          docker-compose exec -T node codeceptjs -c /repo/tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --invert --grep  '@optional'
          pwd
          ls -la codeceptjs/output
      - name: Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: codeceptjs-output
          path: tests/codeceptjs/output
          retention-days: 30
      - name: Test (optional)
        continue-on-error: true
        run: docker-compose exec -T node codeceptjs -c /repo/tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --grep '@optional'

